# Generated by Django 4.2.2 on 2023-10-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
        ),
    ]
